version: '3'
services:
  test:
    build:
      context: test
      dockerfile: Dockerfile
    volumes:
      - .:/sys-sage
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        cmake -S /sys-sage -B /build -DCMAKE_BUILD_TYPE=Debug -DTESTS=ON -DTESTS_ENABLE_SANITIZERS=OFF
        cmake --build build --target test
        ./build/test/test
