on: [push]
jobs:
  test:
    name: Unit Tests
    uses: ./.github/workflows/test.yml
  asan:
    name: Address Sanitizer
    needs: test
    uses: ./.github/workflows/test.yml
    with:
      flags: -DTEST_ASAN=ON
  tsan:
    name: Thread Sanitizer
    needs: test
    uses: ./.github/workflows/test.yml
    with:
      flags: -DTEST_TSAN=ON
  ubsan:
    name: Undefined Behaviour Sanitizer
    needs: test
    uses: ./.github/workflows/test.yml
    with:
      flags: -DTEST_UBSAN=ON
  doc:
    name: Documentation
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - run: pip3 install coverxygen
      - run: doxygen docs/Doxyfile
      - run: python3 -m coverxygen --xml-dir xml --src-dir src/ --output doc-coverage.info --format json-v3
      - run: doc/show_undocumented.py
