on: [push]
env:
  CXX: clang++
  CC: clang
jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/test
  asan:
    runs-on: [ubuntu-latest]
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/test
        with:
          flags: -DTEST_ASAN=ON
