on: [push]
env:
  CXX: clang++
  CC: clang
jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Configure
        shell: bash
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DTEST=ON
      - name: Build
        shell: bash
        run: cmake --build build --target test
      - name: Execute
        shell: bash
        run: ./build/test/test
  asan:
    runs-on: [ubuntu-latest]
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Configure
        shell: bash
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DTEST=ON -DTEST_ASAN=ON
      - name: Build
        shell: bash
        run: cmake --build build --target test
      - name: Execute
        shell: bash
        run: ./build/test/test
  msan:
    runs-on: [ubuntu-latest]
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Configure
        shell: bash
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DTEST=ON -DTEST_MSAN=ON
      - name: Build
        shell: bash
        run: cmake --build build --target test
      - name: Execute
        shell: bash
        run: ./build/test/test
  tsan:
    runs-on: [ubuntu-latest]
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Configure
        shell: bash
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DTEST=ON -DTEST_TSAN=ON
      - name: Build
        shell: bash
        run: cmake --build build --target test
      - name: Execute
        shell: bash
        run: ./build/test/test