name: test
on: [push]
env:
  CXX: clang
  CC: clang
jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - run: mkdir -p build
      - run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DTEST=ON
      - run: cmake --build build --target test
      - run: ./build/test/test
  asan:
    runs-on: [ubuntu-latest]
    needs: test
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - run: mkdir -p build
      - run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DTEST=ON -DTEST_ASAN=ON
      - run: cmake --build build --target test
      - run: ./build/test/test
