name: test
on: [push]
env:
  CXX: clang++
  CC: clang
jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - uses: ./.github/actions/action.yml
  asan:
    runs-on: [ubuntu-latest]
    needs: test
    steps:
      - uses: ./.github/actions/action.yml
        with:
          flags: -DTEST_ASAN=ON
