on: [push]
jobs:
  test:
    name: Unit Tests
    uses: ./.github/workflows/build.yml
  asan:
    name: Address Sanitizer
    needs: test
    uses: ./.github/workflows/build.yml
    with:
      flags: -DTEST_ASAN=ON
  tsan:
    name: Thread Sanitizer
    runs-on: [ubuntu-latest]
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DTEST=ON -DTEST_TSAN=ON
      - name: Build
        run: cmake --build build --target test
      - name: Test
        run: ./build/test/test
  ubsan:
    name: Undefined Behaviour Sanitizer
    runs-on: [ubuntu-latest]
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DTEST=ON -DTEST_UBSAN=ON
      - name: Build
        run: cmake --build build --target test
      - name: Test
        run: ./build/test/test