name: test
on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - run: cmake -S /sys-sage -B /build -DCMAKE_BUILD_TYPE=Debug -DTESTS=ON -DTESTS_ENABLE_SANITIZERS=OFF
      - run: cmake --build build --target test
      - run: ./build/test/test
